name: Deploy Shiny Python App to shinyapps.io

on:
  push:
    branches:
      - shiny-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust if you use pyproject.toml instead

    - name: Deploy to shinyapps.io
      env:
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      run: |
        pip install rsconnect-python
        rsconnect write-manifest
        rsconnect deploy shinyapps.io \
          --name foxlabs \
          --title MSAexplorer \
          --token $SHINYAPPS_TOKEN \
          --secret $SHINYAPPS_SECRET